export {default as Hero} from '@/components/Home/Hero'
export {default as About} from '@/components/Home/About'
export {default as Videos} from '@/components/Home/Videos'
export {default as Services} from '@/components/Home/Services'
export {default as Testimonials} from '@/components/Home/Testimonials'