import Breadcrumb from "@/components/Layout/Breadcrumb";
import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>
          Vekil Emin Kiçikbəyov haqqında. Peşəkar hüquqşunas xidmeti.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb title={'Haqqımda'} />
    </>
  );
}
