import Breadcrumb from "@/components/Layout/Breadcrumb";
import styles from "@/styles/Contacts/Contacts.module.scss";
import {
  faEnvelope,
  faLocationDot,
  faPhone,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";

export default function Contacts() {
  return (
    <div className={styles.contacts}>
      <Head>
        <title>Əlaqə | Vekil Emin Kiçikbəyov.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg"></div>
      <div className="content">
        <Breadcrumb title={"ƏLAQƏ"} />
        <div className="container">
          <div className="contacts__inner">
            <div className="contact__item">
              <div className="icon">
                <FontAwesomeIcon icon={faLocationDot} />
              </div>
              <h1>Ünvan</h1>
              <p>
                Xətai rayonu, 8 noyabr PR 15
                <br /> &#34;Azure Busines Center&#34;
              </p>
            </div>
            <div className="contact__item">
              <div className="icon">
                <FontAwesomeIcon icon={faPhone} />
              </div>
              <h1>Telefon</h1>
              <a href="#">(+994) 70 431 04 01 (Qeydiyyat)</a>
              <a href="#">(+994) 55 431 04 01 (Whatsapp)</a>
              <a href="#">(+994) 12 409 57 40 (Ofis)</a>
            </div>
            <div className="contact__item">
              <div className="icon">
                <FontAwesomeIcon icon={faEnvelope} />
              </div>
              <h1>Email</h1>
              <p>k.emin@vekilbaku.az</p>
            </div>
          </div>
        </div>
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12157.449563795863!2d49.8745032!3d40.3786602!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307d5b16f03049%3A0x8b233276e2e00004!2sAzure%20Business%20Center!5e0!3m2!1sru!2saz!4v1686914397432!5m2!1sru!2saz&zoom=10"
          allowFullScreen=""
          className="iframe"
          height="663px"
          loading="lazy"
          referrerpolicy="no-referrer-when-downgrade"
        ></iframe>
      </div>
    </div>
  );
}
