import Breadcrumb from "@/components/Layout/Breadcrumb";
import styles from "@/styles/Contacts/Contacts.module.scss";
import Head from "next/head";

export default function Contacts() {
  return (
    <div className={styles.contacts}>
      <Head>
        <title>
          Əlaqə | Vekil Emin Kiçikbəyov.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb title={"ƏLAQƏ"} />
    </div>
  );
}
