import Breadcrumb from "@/components/Layout/Breadcrumb";
import { Videos } from "@/components/Home";
import Head from "next/head";
export default function VideosPage() {
  return (
    <>
      <Head>
        <title>
          Videolar | Emin Kiçikbəyov.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Breadcrumb title={"Videoçarxlar"} />
      <Videos />
    </>
  );
}
